version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:8'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: 'npm install'
      - run: 'npm build'
      - run: './node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN'